site_id:        api
theme:          iiifc-theme
source:         source
permalink:      pretty
baseurl:        '/api'

api_url:        ''
root_url:       '/'
cookbook_url:   '/api/cookbook/'

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-liquify
  - jekyll-redirect-from

notification:
  enabled: true
  title: This website design is in pre-beta.
  subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  link: '#'
  link_label: This is a test link

