url:            ''
baseurl:        '/iiif-api'
theme:          iiifc-theme
source:         source
permalink:      pretty

root_url:       'https://marii.info/iiif-website'
api_url:        '/iiif-api/api'

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from

notification:
  enabled: true
  title: This website design is in pre-beta.
  subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  link: '#'
  link_label: This is a test link
